---
- name: Determine/set SSH port
  block:

    - name: Test custom SSH port
      ansible.builtin.wait_for:
        port: "{{ ansible_port }}"
        host: "{{ ansible_host }}"
        timeout: 5
      delegate_to: "localhost"

  rescue:

    - name: Save custom Ansible port to a variable
      ansible.builtin.set_fact:
        custom_ansible_port: "{{ ansible_port }}"

    - name: Test standard SSH port
      ansible.builtin.wait_for:
        port: 22
        host: "{{ ansible_host }}"
        timeout: 5
      delegate_to: "localhost"

    - name: Set Ansible connection port to 22
      ansible.builtin.set_fact:
        ansible_port: 22

    - name: Change OpenSSH listen port
      become: true
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config.d/90-ansible.conf
        regexp: '^Port '
        line: 'Port {{ custom_ansible_port }}'
        insertafter: EOF
        state: present
        validate: 'sshd -tf %s'
        owner: root
        group: root
        mode: '0600'
        create: true

    # This restart is not conditional because we are in the rescue block.
    # Also, we need to use "daemon-reload" because, in Ubuntu 24.04, the
    # systemd configuration is auto-generated by reading /etc/ssh/:
    # https://bugs.launchpad.net/ubuntu/+source/openssh/+bug/2069041
    - name: Restart SSH service
      become: true
      ansible.builtin.systemd_service:
        name: ssh
        daemon_reload: true
        state: restarted

    - name: Set ansible_port to {{ custom_ansible_port }}
      ansible.builtin.set_fact:
        ansible_port: "{{ custom_ansible_port }}"

    - name: Test custom SSH port again
      ansible.builtin.wait_for:
        port: "{{ ansible_port }}"
        host: "{{ ansible_host }}"
        timeout: 10
      delegate_to: "localhost"
