- name: Further hardening
  tags: hardening
  block:

    - name: Disable some insecure SSH options
      become: true
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config.d/90-ansible.conf
        regexp: '^{{ item.key }} '
        line: '{{ item.key }} {{ item.value }}'
        insertafter: EOF
        state: present
        validate: 'sshd -tf %s'
        owner: root
        group: root
        mode: '0600'
        create: true
      with_dict:
        - 'PermitRootLogin': 'no'
        - 'PermitEmptyPasswords': 'no'
        - 'PasswordAuthentication': 'no'
        - 'ChallengeResponseAuthentication': 'no'
        - 'KbdInteractiveAuthentication': 'no'
      notify: reload_ssh
      # Note that AWS uses PAM, so we cannot set UsePAM=no

    - name: Enable passwordless sudo for user {{ ansible_user }}
      become: true
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/90-Ansible
        regexp: '^{{ ansible_user }}'
        line: '{{ ansible_user }} ALL=(ALL) NOPASSWD: ALL'
        state: present
        owner: root
        group: root
        mode: '0440'
        create: true
        validate: 'visudo -cf %s'
