# code language=ansible

- name: Set up firewall
  ansible.builtin.import_tasks: firewall.yml

- name: Prepare system
  ansible.builtin.import_tasks: prepare_system.yml

- name: Install UT2004 server
  ansible.builtin.import_tasks: install_ut2004.yml

- name: Set up dynamic DNS
  ansible.builtin.import_tasks: dynamic_dns.yml

- name: Set up reverse proxy to web admin
  ansible.builtin.import_tasks: nginx.yml

- name: Additional hardening
  ansible.builtin.import_tasks: hardening.yml

- name: Start UT2004 game server
  ansible.builtin.import_tasks: start_ut2004.yml
